### ISSUE TITLE
Baby won't consistently save to file

### ISSUE THREAD

**Issue by optimaaa** [oliveirabruno01/babyagi-asi#10]
Babyagi-asi will perform tasks as suggested. However, it has inconsistencies with saving a file. 

4/17/ - Baby saved a CSV of it's results, as instructed, on it's first run. User opened it, read it, there was data. User closed it, opened it again, ran baby - and poof contents were gone.

Has anyone experienced similar inconsistencies or issues with baby?

**Comment by oliveirabruno01** [comment]
I apologize for the continued delay.. this agent was not initially designed to have a user, so if you want it to save some information you need to ask it explicitly at the prompt (i.e ''search for x and save a summary of the result at file. txt")
