### ISSUE TITLE
It went a bit off the rails XD

### ISSUE THREAD

**Issue by Philomath88** [oliveirabruno01/babyagi-asi#11]
1: Task 76000: Research and identify the best practices
2: Task 100000: Research and identify the best practices for securely storing API keys in mobile applications.
3: Task 104000: Research and identify the best practices for securely storing API keys in web applications.
4: Task 116000: Research and identify the best practices for securely storing API keys in server.
5: Task 132000: Research and identify the best practices for securely storing API keys in desktop application

Anyone got tips how to write the prompt so that it does not go off the rails?

**Comment by Abeansits** [comment]
@Philomath88 can you provide some more context on how it went "off the rails"?

**Comment by Philomath88** [comment]
@Abeansits I don't have the exact logs anymore but you can see that it went to task 132000 (starting from task 1). 

The goal was to develop a python script to allow me to interact with chatgpt

**Comment by Abeansits** [comment]
No worries @Philomath88! 

If you're curious about it you don't really need an agent for that kind of task. The web UI will gladly output that in seconds without costing you anything.
