### ISSUE TITLE
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. (chatgpt free v.)

### ISSUE THREAD

**Issue by zrodrps** [oliveirabruno01/babyagi-asi#5]
Does this work with chatgpt 3 I'm getting this ratelimit error. I only asked for what the time was to test it. I edited the model in .env to gpt-3 from gpt-3.5 turbo

I'm a noob.

**Comment by oliveirabruno01** [comment]
This works with gpt-3.5 and up. Do you remember what task iit were doing at the time you got this error? 

If I'm not mistaken my quota is the standard one too. Try to clone/download the latest version, I'm using it for several different tasks without error, as the requests are synchronous the rate limit and quota has not been a problem

**Comment by IlianP** [comment]
You can change the "hard limit" here: https://platform.openai.com/account/billing/limits
