### ISSUE TITLE
Traceback (most recent call last):   File "/Users/richardhuszar/babyagi-asi/babyagi.py", line 1, in <module>     import openai, prompts, consts, pinecone, os, subprocess, tiktoken, json   File "/Users/richardhuszar/babyagi-asi/prompts.py", line 2, in <module>     import psutil ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by huszarrichard** [oliveirabruno01/babyagi-asi#6]
I got this error:

Traceback (most recent call last):
  File "/Users/richardhuszar/babyagi-asi/babyagi.py", line 1, in <module>
    import openai, prompts, consts, pinecone, os, subprocess, tiktoken, json
  File "/Users/richardhuszar/babyagi-asi/prompts.py", line 2, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

I tried these commands:
`pip install psutil`
`pip3 install psutil`
... and uninstall psutil and reinstall but same problem. Any recommandations? Thank you.

**Comment by Philomath88** [comment]
Same error: 

Traceback (most recent call last):
  File "/Users/maximiliandoelle/Projects/babyagi-asi/babyagi.py", line 1, in <module>
    import openai, prompts, consts, pinecone, os, subprocess, tiktoken, json
  File "/Users/maximiliandoelle/Projects/babyagi-asi/prompts.py", line 9, in <module>
    I am running on a {platform.system()} {platform.architecture()[0]} system with {round(psutil.virtual_memory().total / (1024 ** 3), 2)} GB RAM and a {psutil.cpu_freq().current/1000 if psutil.cpu_freq() else "unknown"} GHz CPU. I am using OpenAI API. I must remember to use '|' instead of '&&' or '&' in my commands if using windows' cmd or pws.
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/psutil/__init__.py", line 1864, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/Users/maximiliandoelle/miniconda3/lib/python3.10/site-packages/psutil/_psosx.py", line 179, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctl(HW_CPU_FREQ))
(base) maximiliandoelle@Maximilians-

**Comment by optimaaa** [comment]
Have you tried `sudo apt-get update` ?

Also, here is an optimized prompt to take whatever errors you get thrown and learn well via GPT:

> “You are now MetaGPT, your job is to use a creative and intuitive metaphor to explain code for me. Whenever I post a code snippet here, you will give me a detailed explanation of the problem the code is trying to solve, the logic of how we could approach the problem to solve it, the description of what the code is doing (don't just read the code line by line, be more creative and explain in broader terms. Don't forget to illustrate your explanations with easily understandable metaphors whenever you think it will add value to the explanation. Make sure to teach this stuff as the world's greatest teachers would. Assume the person you are teaching too is not that smart so like, find a way to explain it to them. Write "MetaGPT: " before every answer. If you understand ,reply now with: "Hey I am MetaGPT! What is the code you want me to explain to you?"

**Comment by Philomath88** [comment]
I have verified with homebrew that everything is up to date:

(base) maximiliandoelle@Maximilians-MBP babyagi % brew update
Already up-to-date.

Your prompt looks sick!

**Comment by Philomath88** [comment]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/125642217/232671415-55061f7a-973e-4c70-9dbe-817ac31fe901.png">

It seems like it is working now. I suspect it was a Pinecone issue (they had quite some demand to deal with in the last couple of days)
