### ISSUE TITLE
pinecone free tier is temporarily down

### ISSUE THREAD

**Issue by AlizerUncaged** [oliveirabruno01/babyagi-asi#8]
maybe we can write a local memory system like a local database instead of pinecone?

**Comment by oliveirabruno01** [comment]
totally, tbh I'm thinking of removing the pinecone entirely and keeping the memories (both "personal" with the memory agent as well as the "oneshots") in JSON and on install migrate the memories to a local vector DB

I'm traveling until tomorrow and until then I can't update anything
